name: Build Flutter App

on:
  push:
    branches:
      - main
    tags:
      - 'v*'

jobs:
  build:
    name: Build Android App
    runs-on: macos-latest
    strategy:
      fail-fast: false
    if: startsWith(github.ref, 'refs/tags/v')
    steps:
      - uses: actions/checkout@v2

      # setup flutter env
      - uses: subosito/flutter-action@v1
        with:
          flutter-version: '2.x'
          channel: 'stable'

      - name: Install Dependencies
        run: flutter pub get

      # - name: Static analysis.
      #   run: flutter analyze .

      # - name: Run tests
      #   run: flutter test

      - name: Build apk
        run: flutter build apk

      - name: Upload apk
        uses: actions/upload-artifact@v2
        with:
          name: release-apk
          path: build/app/outputs/apk/release/app-release.apk

      - name: Build iOS App
        run: |
            flutter build ios --nocodesign
            cd build/ios/iphoneos
            mkdir Payload
            cd Payload
            ln -s ../Runner.app
            cd ..
            zip -r app.ipa Payload

      - name: Push apk, ipa to Releases
        uses: ncipollo/release-action@v1
        with:
          artifacts: "build/app/outputs/apk/release/*.apk,build/ios/iphoneos/app.ipa"
          token: ${{ secrets.GITHUB_TOKEN }}
