name: Build Flutter App

on:
  push:
    branches:
      - main
    tags:
      - 'v*'

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        # parallely build apk on ubuntu, ipa on macos and windows on windows
        os: [macOS-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    if: startsWith(github.ref, 'refs/tags/v')
    steps:
      - uses: actions/checkout@v2

      - name: Setup stable flutter env (*nix)
        if: ${{ runner.os != 'Windows' }}
        uses: subosito/flutter-action@v1
        with:
          flutter-version: '2.x'
          channel: 'stable'

      - name: Setup beta flutter env (Windows)
        if: ${{ runner.os == 'Windows' }}
        uses: subosito/flutter-action@v1
        with:
          flutter-version: '2.x'
          channel: 'beta'

      - name: Install Dependencies
        run: flutter pub get

      # - name: Static analysis.
      #   run: flutter analyze .

      # - name: Run tests
      #   run: flutter test

      - name: Build apk
        if: ${{ runner.os == 'Linux' }}
        run: flutter build apk

      - name: Build iOS App
        if: ${{ runner.os == 'macOS' }}
        run: |
            flutter build ios --no-codesign
            cd build/ios/iphoneos
            mkdir Payload
            cd Payload
            ln -s ../Runner.app
            cd ..
            zip -r app.ipa Payload

      - name: Build windows app
        if: ${{ runner.os == 'Windows' }}
        run: |
            flutter config --enable-windows-desktop
            flutter build windows
      
      - name: Upload APK
        if: ${{ runner.os == 'Linux' }}
        uses: actions/upload-artifact@v2
        with:
          name: bins
          path: |
                build/app/outputs/apk/release/*.apk

      - name: Upload IPA
        if: ${{ runner.os == 'macOS' }}
        uses: actions/upload-artifact@v2
        with:
          name: bins
          path: |
                build/ios/iphoneos/app.ipa
      
      - name: Upload windows executable bundle
        if: ${{ runner.os == 'Windows' }}
        run: tar -a -c -f windows_executable.zip build/windows/runner/Release
        uses: actions/upload-artifact@v2
        with:
          name: bins
          path: windows_executable.zip
                

  release:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - uses: actions/checkout@v2

      - uses: actions/download-artifact@v2
        id: downID
        with:
          name: bins
          path: build # download to ./build/

      - name: Push artificats to Releases
        uses: ncipollo/release-action@v1
        with:
          artifacts: |
                    build/app/outputs/apk/release/*.apk
                    build/ios/iphoneos/app.ipa
                    build/windows/runner/Release/*
          token: ${{ secrets.GITHUB_TOKEN }}


      
