name: Build Flutter App

on:
  push:
    branches:
      - main

jobs:
  build:
    name: Build APK
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      # setup flutter env
      - uses: subosito/flutter-action@v1
        with:
          flutter-version: '2.x'
          channel: 'stable'

      - name: Install Dependencies
        run: flutter pub get

      - name: Statically analysis.
        run: flutter analyze .

      - name: Run tests
        run: flutter test

      - name: Build Android App
        run: flutter build apk

      # Upload generated apk to the artifacts.
      - uses: actions/upload-artifact@v1
        with:
          name: release-apk
          path: build/app/outputs/apk/release/connstw-release.apk