name: Build Flutter App

on:
  push:
    branches:
      - main
    tags:
      - 'v*'

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        os: [macOS-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    if: startsWith(github.ref, 'refs/tags/v')
    steps:
      - uses: actions/checkout@v2

      - name: Setup stable flutter env
        if: ${{ runner.os != 'Windows' }}
        uses: subosito/flutter-action@v1
        with:
          flutter-version: '2.x'
          channel: 'stable'

      - name: Setup beta flutter env (Windows)
        if: ${{ runner.os == 'Windows' }}
        uses: subosito/flutter-action@v1
        with:
          flutter-version: '2.x'
          channel: 'beta'

      - name: Install Dependencies
        run: flutter pub get

      # - name: Static analysis.
      #   run: flutter analyze .

      # - name: Run tests
      #   run: flutter test

      - name: Build apk
        if: ${{ runner.os == 'macOS' }}
        run: flutter build apk

      - name: Build iOS App
        if: ${{ runner.os == 'macOS' }}
        run: |
            flutter build ios --no-codesign
            cd build/ios/iphoneos
            mkdir Payload
            cd Payload
            ln -s ../Runner.app
            cd ..
            zip -r app.ipa Payload

      - name: Build windows app
        if: ${{ runner.os == 'Windows' }}
        run: |
            flutter config --enable-windows-desktop
            flutter build windows
      
      - name: Upload apk, ipa, exe
        uses: actions/upload-artifact@v2
        with:
          name: bins
          path: |
                build/app/outputs/apk/release/*.apk
                build/ios/iphoneos/app.ipa
                build/windows/runner/Release/*

      # - name: Push apk, ipa to Releases
      #   if: ${{ runner.os == 'macOS' }}
      #   uses: ncipollo/release-action@v1
      #   with:
      #     artifacts: |
      #               build/app/outputs/apk/release/*.apk
      #               build/ios/iphoneos/app.ipa
      #               build/windows/runner/Release/*

  release:
    runs-on: ubuntu-latest
    needs: build
    # if: startsWith(github.ref, 'refs/tags/v')
    steps:
      - uses: actions/checkout@v2

      - uses: actions/download-artifact@v2
        with:
          name: bins
          path: downloaded-bins

      - name: Push apk, ipa to Releases
        if: ${{ runner.os == 'macOS' }}
        uses: ncipollo/release-action@v1
        with:
          artifacts: "downloaded-bins/*"
          token: ${{ secrets.GITHUB_TOKEN }}


      
